version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    command: npm run start:dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mongo
    environment:
      MONGO_URI: 'mongodb://mongo:27017/quizdb'

  mongo:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
