version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    command: npm run start:dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mongo
    networks:
      - my_network
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017

  mongo:
    image: mongo:5.0
    ports:
      - '27021:27017'
    networks:
      - my_network
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  my_network:
